-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Apr 03, 2016 at 04:15 AM
-- Server version: 5.6.17
-- PHP Version: 5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `aptitude_test`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE IF NOT EXISTS `admin` (
  `cutoffVBR` int(10) NOT NULL,
  `cutoffQLR` int(11) NOT NULL,
  `cutoffQNR` int(11) NOT NULL,
  `examstart` varchar(50) NOT NULL,
  `examend` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`cutoffVBR`, `cutoffQLR`, `cutoffQNR`, `examstart`, `examend`) VALUES
(4, 4, 4, '2016-04-01 00:56:18', '2016-04-02 00:56:18');

-- --------------------------------------------------------

--
-- Table structure for table `livetest`
--

CREATE TABLE IF NOT EXISTS `livetest` (
  `userid` int(50) NOT NULL,
  `testname` varchar(50) NOT NULL,
  `qnum` int(50) NOT NULL,
  `question` text NOT NULL,
  `a` text NOT NULL,
  `b` text NOT NULL,
  `c` text NOT NULL,
  `d` text NOT NULL,
  `correctanswer` varchar(50) NOT NULL,
  `useranswer` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `livetesttime`
--

CREATE TABLE IF NOT EXISTS `livetesttime` (
  `userid` int(50) NOT NULL,
  `testname` varchar(50) NOT NULL,
  `starttime` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `questionbank`
--

CREATE TABLE IF NOT EXISTS `questionbank` (
  `testname` varchar(50) NOT NULL,
  `qnum` int(50) NOT NULL,
  `question` text NOT NULL,
  `a` text NOT NULL,
  `b` text NOT NULL,
  `c` text NOT NULL,
  `d` text NOT NULL,
  `correctanswer` varchar(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `questionbank`
--

INSERT INTO `questionbank` (`testname`, `qnum`, `question`, `a`, `b`, `c`, `d`, `correctanswer`) VALUES
('vbr', 1, 'Ishaan Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'c'),
('vbr', 2, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 3, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 4, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 5, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 6, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 7, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 8, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 9, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 10, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 11, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 12, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 13, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 14, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 15, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 16, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 17, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 18, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 19, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 20, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 21, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 22, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 23, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 24, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 25, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 26, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 27, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 28, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 29, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 30, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 31, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 32, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 33, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 34, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 35, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 36, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 37, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 38, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 39, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 40, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 41, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 42, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 43, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 44, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 45, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 46, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 47, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 48, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 49, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('vbr', 50, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 1, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 2, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 3, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 4, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 5, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 6, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 7, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 8, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 9, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 10, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 11, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 12, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 13, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 14, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 15, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 16, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 17, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 18, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 19, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 20, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 21, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 22, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 23, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 24, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 25, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 26, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 27, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 28, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 29, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 30, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 31, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 32, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 33, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 34, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 35, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 36, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 37, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 38, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 39, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 40, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 41, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 42, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 43, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 44, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 45, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 46, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 47, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 48, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 49, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qnr', 50, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 1, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 2, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 3, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 4, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 5, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 6, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 7, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 8, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 9, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 10, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 11, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 12, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 13, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 14, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 15, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 16, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 17, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 18, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 19, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 20, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 21, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 22, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 23, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 24, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 25, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 26, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 27, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 28, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 29, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 30, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 31, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 32, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 33, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 34, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 35, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b');
INSERT INTO `questionbank` (`testname`, `qnum`, `question`, `a`, `b`, `c`, `d`, `correctanswer`) VALUES
('qlr', 36, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 37, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 38, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 39, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 40, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 41, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 42, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 43, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 44, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 45, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 46, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 47, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 48, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 49, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b'),
('qlr', 50, 'Dummy Question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question dummy question\r\n					 dummy question dummy question dummy question', 'Option a choose an option', 'Option b choose an option', 'Option c choose an option', 'Option d choose an option', 'b');

-- --------------------------------------------------------

--
-- Table structure for table `results`
--

CREATE TABLE IF NOT EXISTS `results` (
  `userid` int(10) NOT NULL,
  `marksQNR` int(10) NOT NULL,
  `marksQLR` int(10) NOT NULL,
  `marksVBR` int(10) NOT NULL,
  `total` int(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `userid` int(11) NOT NULL AUTO_INCREMENT,
  `fullname` varchar(30) NOT NULL,
  `username` varchar(30) NOT NULL,
  `password` varchar(100) NOT NULL,
  `email` varchar(40) NOT NULL,
  `gender` varchar(10) NOT NULL,
  `contact` varchar(30) NOT NULL,
  `address` varchar(30) NOT NULL,
  `examflag` int(5) NOT NULL,
  PRIMARY KEY (`userid`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=17 ;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`userid`, `fullname`, `username`, `password`, `email`, `gender`, `contact`, `address`, `examflag`) VALUES
(-99, 'Administrator', 'admin', 'QrGj3NyVMD69FUgANhf1JAIAW1I+dRG4n7fhOr6y2YU=', 'N/A', 'N/A', 'N/A', 'N/A', 0),
(16, 'Ishaan Shringi', 'ishaan', '25y9/TAY8Ud/1unxH5H1bR6r98bpyHy496YrZdDEN4w=', 'shringiishaan@gmail.com', 'male', '123456789', 'Surat  ', 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
